### ISSUE TITLE
error at installation

### ISSUE THREAD

**Issue by trebmuh** [JocelynDelalande/autolink3#1]
Hi,
when installing this plugin through the Dokuwiki extension manager, the plugin keep saying that a new version is available. Updating  doesn't this notice to disappear. 
Tested on Dokuwiki 2015-08-10a "Detritus", this day.

**Comment by JocelynDelalande** [comment]
@trebmuh I'm neither author or maintainer, that was just a personal fork, and I even forgot why I did it 3 years ago. Sorry. Isn't any "official" forge/tracker around ?

**Comment by trebmuh** [comment]
Thanks for the answer. I was hoping that you were still involved with it but, no luck it looks :)
Anyway, I'll be trying to contact the people mentionned on https://www.dokuwiki.org/plugin:autolink3 

Pas de soucis, merci.
